services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-whatsapp-api}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${HOST_BIND:-0.0.0.0}:5656:5656"
    # These volumes persist your session data even when containers are stopped
    volumes:
      - ${SESSIONS_PATH:-./sessions}:/usr/src/app/sessions       # WhatsApp session data (PERSISTENT)
      - ${AUTH_PATH:-./.wwebjs_auth}:/usr/src/app/.wwebjs_auth  # WhatsApp auth data & Chrome profiles (PERSISTENT)
      - ${CACHE_PATH:-./.cache}:/usr/src/app/.cache           # Cache data (PERSISTENT)
      - ${LOGS_PATH:-./logs}:/usr/src/app/logs               # Application logs (PERSISTENT)
    environment:
      - PORT=5656
      - API_KEY=${API_KEY:-0cecfcdb-0cdb-4463-91ba-9f70dbd4f6f2}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:-http://host.docker.internal:5656/callback}
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=${ENABLE_LOCAL_CALLBACK_EXAMPLE:-TRUE}
      - MAX_ATTACHMENT_SIZE=${MAX_ATTACHMENT_SIZE:-10000000}
      - SET_MESSAGES_AS_SEEN=${SET_MESSAGES_AS_SEEN:-TRUE}
      - DISABLED_CALLBACKS=${DISABLED_CALLBACKS:-message_ack|message_reaction|unread_count|message_edit|message_ciphertext}
      - ENABLE_SWAGGER_ENDPOINT=${ENABLE_SWAGGER_ENDPOINT:-TRUE}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-1000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-1000}
      - WEB_VERSION=${WEB_VERSION:-'2.2328.5'}
      - WEB_VERSION_CACHE_TYPE=${WEB_VERSION_CACHE_TYPE:-none}
      - RECOVER_SESSIONS=${RECOVER_SESSIONS:-TRUE}
      - CHROME_HEADLESS=${CHROME_HEADLESS:-TRUE}
      - SESSIONS_PATH=${SESSIONS_PATH:-./sessions}
      # Docker/Container specific environment variables
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CHROME_BIN=/usr/bin/chromium-browser
      - PUPPETEER_DEBUG=${PUPPETEER_DEBUG:-FALSE}
      - NODE_ENV=${NODE_ENV:-production}
      - DISPLAY=:99
    # Add capabilities needed for Chrome/Puppeteer to work properly in Docker
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: ${SHM_SIZE:-2gb}  # Increased shared memory for better Chrome performance
    # Memory limits to prevent container from consuming too much memory
    mem_limit: ${MEM_LIMIT:-4g}
    memswap_limit: ${MEMSWAP_LIMIT:-4g}
    # CPU limits
    cpus: ${CPU_LIMIT:-2.0}
    # Enhanced health check using the comprehensive health endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "x-api-key: ${API_KEY:-0cecfcdb-0cdb-4463-91ba-9f70dbd4f6f2}", "http://localhost:5656/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-60s}



# Named volumes for better performance (optional)
volumes:
  sessions_data:
  auth_data:
  cache_data:
  logs_data:

