services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "0.0.0.0:5656:5656"

    # These volumes persist your session data even when containers are stopped
    volumes:
      - ./sessions:/usr/src/app/sessions       # WhatsApp session data (PERSISTENT)
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth  # WhatsApp auth data & Chrome profiles (PERSISTENT)
      - ./.cache:/usr/src/app/.cache           # Cache data (PERSISTENT)
    environment:
      - PORT=5656
      - API_KEY=${API_KEY:-0cecfcdb-0cdb-4463-91ba-9f70dbd4f6f2}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:-https://app.remlic.co.za/callback}
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=${ENABLE_LOCAL_CALLBACK_EXAMPLE:-TRUE}
      - MAX_ATTACHMENT_SIZE=${MAX_ATTACHMENT_SIZE:-10000000}
      - SET_MESSAGES_AS_SEEN=${SET_MESSAGES_AS_SEEN:-TRUE}
      - DISABLED_CALLBACKS=${DISABLED_CALLBACKS:-message_ack|message_reaction|unread_count|message_edit|message_ciphertext}
      - ENABLE_SWAGGER_ENDPOINT=${ENABLE_SWAGGER_ENDPOINT:-TRUE}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-1000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-1000}
      - WEB_VERSION=${WEB_VERSION:-'2.2328.5'}
      - WEB_VERSION_CACHE_TYPE=${WEB_VERSION_CACHE_TYPE:-none}
      - RECOVER_SESSIONS=${RECOVER_SESSIONS:-TRUE}
      - CHROME_HEADLESS=${CHROME_HEADLESS:-TRUE}
      - SESSIONS_PATH=${SESSIONS_PATH:-./sessions}
    # Add capabilities needed for Chrome/Puppeteer to work properly in Docker
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: 1gb
    networks:
      - nginx-proxy_default

networks:
  nginx-proxy_default:
    external: true


