services:
  app:
    container_name: whatsapp_web_api
    build: .  # Build from local Dockerfile instead of using remote image
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env  # Use environment variables from .env file
    volumes:
      - ./sessions:/usr/src/app/sessions  # Persist sessions between container restarts
    healthcheck:  # Add healthcheck to ensure container is running properly
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
